apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hermes-api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "256k"
spec:
  rules:
    - host: hermes.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hermes-api
                port:
                  number: 80
  tls:
    - hosts:
        - hermes.local
      secretName: hermes-tls

