apiVersion: v1
kind: Service
metadata:
  name: hermes-api
  labels:
    app: hermes-api
spec:
  selector:
    app: hermes-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP

